# Generated by Django 4.2.21 on 2025-05-29 15:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_post_options_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='new_field',
            field=models.SlugField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
