# Generated by Django 4.2.21 on 2025-05-30 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_comment_new_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='new_field',
            field=models.SlugField(blank=True, null=True, verbose_name='Slug or Tag (optional)'),
        ),
    ]
