# Generated by Django 4.2.21 on 2025-05-31 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_post_featured_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='new_field',
        ),
    ]
